### ISSUE TITLE
Future Data Driven Summit Event

### ISSUE THREAD

**Issue by way0utwest** [sqlsaturday/sqlsatwebsite#1]
New event for  Sep-29-2021 
Sessionize: https://sessionize.com/FutureDataDriven

If you want to list this as an "other event" I can add that. If you have a logo, please let me know where a small image is located, or add as part of a PR for the /assets/img/logos folder.

For listing as a main event, I think we'd want the name to be SQL Saturday Future Data Driven 2021 (or something similar)

Tagging @ bigdatadriven

**Comment by bigdatadriven** [comment]
Thank you much @way0utwest for your quick response and support!

The name of the event is "**Future Data Driven Summit**" and the date is Sep-29-2021.

The logo of the event can be found here: https://github.com/bigdatadriven/FutureDataDriven/blob/main/FDD_logo.PNG

Feel free to reach out to me for any additional information.

Best Regards,
Jean Joseph

**Comment by way0utwest** [comment]
Is there a URL for the event itself?

We are not hosting other events on the site here, but are happy to link to them. As I mentioned above, if you want to give this a SQL Saturday name, happy to host the event here.

**Comment by bigdatadriven** [comment]
Hello Steve,

Thank you so much for your quick response!

Please find the URL below:
https://www.meetup.com/cloud-data-driven/events/278371356/

@way0utwest

**Comment by way0utwest** [comment]
Updated.
