### ISSUE TITLE
SQLSaturday Denver 2023

### ISSUE THREAD

**Issue by b5lurker** [sqlsaturday/sqlsatwebsite#134]
Event Title (required) - SQLSaturday Denver 2023
Event Date (required): 9/23/2023
Event Time (optional): 8am MT
Event description (required): 
Denver's 11th SQLSaturday event is a FREE day of training sessions for Microsoft Data Platform professionals and those wanting to grow their skill set in the Microsoft Data Platform both on-premises and in the cloud. This event is being hosted by Denver SQL Server Users Group.

SQLSaturday is a training event for SQL Server and data professionals who want to learn how to elevate their careers to the next level. This is the 11th SQLSaturday in Denver and will be held on September 23, 2023. Admittance to this event is FREE, all costs are covered by donations and sponsorship. Please register soon as seating is limited, and let friends and colleagues know about the event. SQLSaturday Denver is hosted by Denver SQL Server Users Group.

Why Attend? This is a great opportunity to learn from SQL Server Experts, Microsoft MVPs, SQL Server Authors, and Professionals who have been through and can relate to the obstacles you have day to day. This one day training event is unlike any other providing free food, training and networking.
Event Location (required): Lowry Conference Center, 1061 Akron Way, Denver, CO 80230
Event URL (optional): None
Logo URL (optional): Default
Speaker CFP URL (optional): https://sessionize.com/sqlsaturday-denver-2023/
Speaker CFP End Date (optional): 5/31/2023 11:59pm MT
Registration URL for attendees (optional): https://www.eventbrite.com/e/sqlsaturday-denver-2023-tickets-566987283227
Sponsor Plan URL (optional): TBD
Organizer name(s) (required): Denver SQL Server User Group
Contact email (required): board@denversql.org

**Comment by b5lurker** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/swake/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/swake/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Event Title | SQLSaturday Denver 2023
-- | --
Event Date | 9/23/2023
Event Time | 8:00am - 4:30pm MT
Event Capacity | 250
CFP URL | https://sessionize.com/sqlsaturday-denver-2023/
CFP End Date | 5/31/2023   11:59pm MT
Registration URL | TBD
Event Location | Lowry   Conference Center, 1061 Akron Way, Denver, CO 80230
Event Description | Denver's 11th SQLSaturday event is one FREE day of training sessions for Microsoft Data Platform   professionals and those wanting to grow their skill set in the Microsoft Data Platform both on-premises and in the cloud. This event is being hosted by Denver SQL Server Users Group. </p>SQLSaturday is a training event for SQL Server and data professionals who want to learn how to elevate their careers to the next level. This is the 11th SQLSaturday in Denver and will be held on September 23, 2023. Admittance to this event is FREE, all costs are covered by donations and sponsorship. Please register soon as seating is limited, and let friends and colleagues know about the event. SQLSaturday Denver is hosted by Denver SQL Server Users Group.</p>Why Attend? This is a great opportunity to learn from SQL Server Experts, Microsoft MVPs, SQL Server Authors, and Professionals who have been through and can relate to the obstacles you have day to day. This one day training event is unlike any other providing free food, training and networking.
Organizer Name | Denver SQL Server User Group
Contact Email | board@denversql.org
Contact URL | https://www.meetup.com/denver-sql-server-user-group/
Twitter account for organizer/group | @DenverSQL
Sponsor Plan URL | TBD
Sponsorship plan | TBD
Logo URL (<200x100) |  
Logo URL (full size for event page) |  
Using Rooms for Virtual? | No
Precons? | No
Precon details |  
Youtube |  
LinkedIn | https://www.linkedin.com/groups/1789566/



</body>

</html>

**Comment by way0utwest** [comment]
1056 assigned. Test page at: https://sqlsaturday.com/2023-09-23-sqlsaturday1056/

When ready to go live, let me know and I will redirect /denver to this page.

The main things for go live: 
- make the CFS live (says test)
- reg link
- sponsorship plan
- anything else that matters for marketing.

**Comment by b5lurker** [comment]
Thanks for getting the page up in test so fast! :)

The CFS page will go live tomorrow (3/1/23 @ midnight MT) and the registration page on Eventbrite will also go live tomorrow morning (3/1/23 @ 10am MT).

Here is the registration link:
https://www.eventbrite.com/e/sqlsaturday-denver-2023-tickets-566987283227

Found one small text tweak needed on the first sentence of the description ("is one FREE day" to "is a FREE day") :
Denver's 11th SQLSaturday event is a FREE day of training sessions...

We will be working on the sponsorship plan and plan to get it ready early next week. Go ahead and go live with this tomorrow once both the CFS and Eventbrite links are live! :)

Glad to have a 6 month head start on it this year, time will still fly by though.

Steve

**Comment by b5lurker** [comment]
Hey Steve, we finally have the links and everything finalized for our Sponsorship Plan! See below:

[Sponsorship Plans 2023.docx](https://github.com/sqlsaturday/sqlsatwebsite/files/11277277/Sponsorship.Plans.2023.docx)

Thanks!
Steve

**Comment by way0utwest** [comment]
This is updated
