### ISSUE TITLE
SQL Saturday Columbus 2023

### ISSUE THREAD

**Issue by pshore73** [sqlsaturday/sqlsatwebsite#144]
[EventChecklist (version 1) Columbus.xlsb.xlsx](https://github.com/sqlsaturday/sqlsatwebsite/files/11067815/EventChecklist.version.1.Columbus.xlsb.xlsx)

**Comment by way0utwest** [comment]
Event opened at: https://sqlsaturday.com/2023-07-15-sqlsaturday1058/

Also, https://sqlsaturday.com/columbus/ is a short code.

Sponsorship plan would be good to add to this.

**Comment by pshore73** [comment]
Thank you!

There is a spot on the call for speakers page what says it ends on 31 Aug 2023, right after it says it ends on April 30, 2023, the latter is correct. Do I submit an issue via GitHub for that?

**Comment by way0utwest** [comment]
Updated with correct cfs
