### ISSUE TITLE
SQLSaturday Belo Horizonte 2023

### ISSUE THREAD

**Issue by maruanafif** [sqlsaturday/sqlsatwebsite#226]
[EventChecklist_SQLBH2023.xlsx](https://github.com/sqlsaturday/sqlsatwebsite/files/12189688/EventChecklist_SQLBH2023.xlsx)

**Comment by fabiojsousa** [comment]
Can't wait for that great event

**Comment by way0utwest** [comment]
I’ve loaded a page here: https://sqlsaturday.com/2023-10-21-sqlsaturday1063/

The main thing to get going is a CFS and Registration URL. We typically recommend using:
Cfs – Sessionize https://sessionize.com/
Registation: Eventbrite: https://www.eventbrite.com/



Steve Jones
Redgate Software

***@***.***<https://www.redgate.com/>

Twitter<https://twitter.com/way0utwest>    |   LinkedIn<https://www.linkedin.com/in/way0utwest>   |   YouTube<https://www.youtube.com/user/RedGateVideos>

**Comment by maruanafif** [comment]
Hi , @way0utwest 

How are you?

Our call for papers link: https://sessionize.com/sql-saturday-belo-horizonte-2023/

Our link are attendant now: https://www.sympla.com.br/evento/sql-saturday-belo-horizonte-2023-1063/2114587

Our link are Sponsorship now: https://docs.google.com/forms/d/e/1FAIpQLSffYRGNUl3pnLI_QGSvwEv0vJ3TOI6ynFPrbB4aPvCOND5IyQ/viewform


sponsorship plan:

Bronze – R$ 500,00

* Distribution of printed material with the Badge.
* Mailing List of participants who accept to receive contact from sponsors.

Silver – R$ 1000,00

* Bronze Plan
* Space in the area dedicated to sponsors.
* Disclosure on the shirt of volunteers Plano Bronze


Gold – R$ 2000,00

* Silver Plan
* Front disclosure on badge
* Disclosure on shirt speakers
* Disclosure in the Backdrop
* Participation in the final draw

**Comment by way0utwest** [comment]
Updated

**Comment by fabiojsousa** [comment]
@maruanafif Do you know if we can park inside the PUC?

**Comment by maruanafif** [comment]
@way0utwest 
Could you insert this information on our event page?
   * Countdown
   * Map event location
   * Sponsors logo
   * Photo and bio of speakers

Follow the archives of sponsors and speakers.

[sql-saturday-belo-horizonte-2023 flattened accepted sessions - exported 2023-10-01.xlsx](https://github.com/sqlsaturday/sqlsatwebsite/files/12777681/sql-saturday-belo-horizonte-2023.flattened.accepted.sessions.-.exported.2023-10-01.xlsx)

[Patrocinadores PSD-20231001T163057Z-001.zip](https://github.com/sqlsaturday/sqlsatwebsite/files/12777682/Patrocinadores.PSD-20231001T163057Z-001.zip)

Thank you!

**Comment by way0utwest** [comment]
Please publish the schedule on sessionize and then enable an API endpoint. This should give you a URL like this one for Denver: https://sessionize.com/api/v2/rm1t6mmb/view/GridSmart

The speaker one will have the same API key with a different URL

**Comment by way0utwest** [comment]
Map is added

**Comment by maruanafif** [comment]
@way0utwest 
Follow the api link.
<script type="text/javascript" src="https://sessionize.com/api/v2/coxnyizh/view/GridSmart"></script>
<script type="text/javascript" src="https://sessionize.com/api/v2/coxnyizh/view/Sessions"></script>
<script type="text/javascript" src="https://sessionize.com/api/v2/coxnyizh/view/Speakers"></script>
<script type="text/javascript" src="https://sessionize.com/api/v2/coxnyizh/view/SpeakerWall"></script>

**Comment by maruanafif** [comment]
@way0utwest 
Could you insert this information on our event page?

- Countdown
- Sponsors logo
- Photo and bio of speakers
- schedule speakers

**Comment by way0utwest** [comment]
Apologies. I am working on this. The countdown, schedule ,and speakers are up. For sponsors, I need:

- image files, not photshop files (jpg/gif/png)
- sponsor URL to link to
- sponsor type (gold, silver, bronze, etc.)

**Comment by maruanafif** [comment]
[SponsorsLogo.zip](https://github.com/sqlsaturday/sqlsatwebsite/files/12974034/SponsorsLogo.zip)
@way0utwest 
Could you insert this information on our event page?

- Sponsors log


Otus7 = Gold  (https://otus7.com/)
One Way = Gold (https://theplumbers.com.br/)
DB Academy = Silver  (https://dbaacademy.com.br/)
CloudAndDdata = Silver (the sponsor did not inform the website)
Crazy = Silver (https://www.crazytechlabs.com.br/)
Seu Chatgpt = free organizer (https://seuchatgpt.com/)
DGA = free organizer (https://www.dgasolutions.com.br/)

**Comment by way0utwest** [comment]
@maruanafif I cannot. As I mentioned in the previous comment, these are PSD files. I need a jpg/png/gif for the site.

Please email me at admin@sqlsaturday.com if you have questions

**Comment by maruanafif** [comment]
@way0utwest 
[mapa-pucminas.pdf](https://github.com/sqlsaturday/sqlsatwebsite/files/12974340/mapa-pucminas.pdf)

Could you add the university map.

**Comment by maruanafif** [comment]
@way0utwest 
Could you insert this information on our event page? 
**rectified in png**
[SponsorsLogo_png.zip](https://github.com/sqlsaturday/sqlsatwebsite/files/12974462/SponsorsLogo_png.zip)


Sponsors log
Otus7 = Gold (https://otus7.com/)
One Way = Gold (https://theplumbers.com.br/)
DB Academy = Silver (https://dbaacademy.com.br/)
CloudAndDdata = Silver (the sponsor did not inform the website)
Crazy = Silver (https://www.crazytechlabs.com.br/)
Seu Chatgpt = free organizer (https://seuchatgpt.com/)
DGA = free organizer (https://www.dgasolutions.com.br/)

**Comment by maruanafif** [comment]
@way0utwest 

Could include Volunteers
in a list?
example:

- Floriano Silva
- Jefferson Hyago
- Reinilson Rodrigues Silva Jr
- Rodrigo Araújo
- Tiago Emílio de Morais

**Comment by maruanafif** [comment]
@way0utwest 

Could include Organizers
in a list?
example:

- Leonardo Côco
- Maruan Aawar
- Mateus Henrique Cândido de Oliveira
- Sulamita Dantas
- Vinicius Fonseca

**Comment by way0utwest** [comment]
list added. Let me know if it looks ok

**Comment by maruanafif** [comment]
@way0utwest 

The sponsors' logo is not appearing and only the writing, I sent you the png above.

All that remains is to insert the names of volunteers into the list.

and adjust the names of organizers in the list.

**Comment by maruanafif** [comment]
@way0utwest 

You need to correct the category too.

Seu Chatgpt = free organizer (https://seuchatgpt.com/)

**Comment by maruanafif** [comment]
@way0utwest 

- the cloud and data logo has a hyperlink pointing to the wrong website, it does not need a hyperlink.
- The writing cloud and data is on the website, please delete it and leave only the image.
- missing to insert the image and hyperlink;  (Crazy = Silver (https://www.crazytechlabs.com.br/))

**Comment by way0utwest** [comment]
The site doesn't have a facility for no link. The point for sponsors is to have a place for attendees to go, so I can't remove the hyperlink for now. I don't know what you want to do here, but need a link to put Cloud and Data as a sponsor.

Removed the text for now. Crazy should be linked and shown.

**Comment by maruanafif** [comment]
@way0utwest 

The sponsor Cloud and Data did not inform the website, apparently it should not have one.
It's not my fault he doesn't have a website.
If it passes I'll let you know.

**Comment by way0utwest** [comment]
I can add his name, but the link will be back to the same page. I can link anywhere, (twttier, linked in, etc.) if he wants

**Comment by maruanafif** [comment]
@way0utwest 

I had to do some research to find the website because the sponsor doesn't respond.

but follow his website.

CloudAndDdata = Silver

https://cloudandata.com.br/

**Comment by maruanafif** [comment]
@way0utwest 

the other changes are correct.
Thank you for your attention.

**Comment by maruanafif** [comment]
@way0utwest 

I received Sulamita request to change the sponsor Crazy = Gold (https://www.crazytechlabs.com.br/) category to the gold category.
Kindly make the change.

**Comment by maruanafif** [comment]
@way0utwest 

could change the name Jefferson Hyago to Fabio Sousa on the list of volunteers, the others were present.

Thank you very much for your support at our SQL Saturday in Belo Horizonte!

**Comment by maruanafif** [comment]
@way0utwest 

update the organizer contacts hyperlink @SqlBh to direct to our Instagram. (https://www.instagram.com/sql.bh/)

**Comment by way0utwest** [comment]
changed the volunteer name. I've added the instragram to the list of socials. Right now, you have twitter, linked in, meetup, and instagram linked.

**Comment by way0utwest** [comment]
Event complete: [attendance](https://github.com/sqlsaturday/sqlsatwebsite/blob/main/assets/misc/2023/2023_Attendance.xlsx)
