### ISSUE TITLE
SQLSaturday Vitória 2023

### ISSUE THREAD

**Issue by fabricio-powertuning** [sqlsaturday/sqlsatwebsite#233]
[Planilha SQLSAT VIX.xlsx](https://github.com/sqlsaturday/sqlsatwebsite/files/12285718/Planilha.SQLSAT.VIX.xlsx)

**Comment by way0utwest** [comment]
Temp site up at: https://www.sqlsaturday.com/vitoria

A few things, and please ask questions to admin@sqlsaturday.com if you need to. If you send an email, I can share my list of sponsor contacts.

- This site isn't up: dataes.com.br (WP error)
- Do you have a reg and CFS url? I would create the sessionize.com CFS and set this for ending sometime in Sept. 
- For reg, Eventbrite works well for free events.
- Does the group have any other Twitter/Threads/Facebook/Youtube/etc link?
- Any sponsorship plan?

**Comment by fabricio-powertuning** [comment]
Hi Steve,

We are working on this information to send you back.

Thanks for your time.

Atenciosamente,


***@***.***

De: Steve Jones ***@***.***>
Enviada em: terça-feira, 8 de agosto de 2023 13:47
Para: sqlsaturday/sqlsatwebsite ***@***.***>
Cc: Fabricio Lima ***@***.***>; Author ***@***.***>
Assunto: Re: [sqlsaturday/sqlsatwebsite] SQLSaturday Vitória 2023 (Issue #233)


Temp site up at: https://www.sqlsaturday.com/vitoria

A few things, and please ask questions to ***@***.******@***.***> if you need to. If you send an email, I can share my list of sponsor contacts.

  *   This site isn't up: dataes.com.br (WP error)
  *   Do you have a reg and CFS url? I would create the sessionize.com CFS and set this for ending sometime in Sept.
  *   For reg, Eventbrite works well for free events.
  *   Does the group have any other Twitter/Threads/Facebook/Youtube/etc link?
  *   Any sponsorship plan?

**Comment by way0utwest** [comment]
Thanks, I am updating. A few things still missing:
- Registration URL
- What do the sponsorships include? You can look at other events (like this one: https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAEZd0wzH-RURUQ4RlpHN0owTE9HWThIRlpXUFMyODdENS4u) for details

**Comment by fabricio-powertuning** [comment]
We write this info in Portuguese:

Bronze – R$ 500,00

- Marca exposta em todos os slides das palestras com menos destaque.
- Marca exposta no material de divulgacao do evento.

Prata – R$ 1000,00

- Marca exposta com mais destaque no slide das palestras
- Possibilidade de levar banner e deixar exposto no dia do evento
- Usuários que derem OK para recebimento de e-mail, enviaremos a lista de e-mails.
- Caso queira enviar, pode entrega algum material publicitário ao kit do participante (panfleto, cartão, etc)

Ouro – R$ 2000 ,00

- Todos os anteriores
- Direito a colocar uma mesa no evento para apresentação da marca/produtos.

Atenciosamente,


***@***.***

De: Steve Jones ***@***.***>
Enviada em: terça-feira, 22 de agosto de 2023 12:36
Para: sqlsaturday/sqlsatwebsite ***@***.***>
Cc: Fabricio Lima ***@***.***>; Author ***@***.***>
Assunto: Re: [sqlsaturday/sqlsatwebsite] SQLSaturday Vitória 2023 (Issue #233)


Thanks, I am updating. A few things still missing:

  *   Registration URL
  *   What do the sponsorships include? You can look at other events (like this one: https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAEZd0wzH-RURUQ4RlpHN0owTE9HWThIRlpXUFMyODdENS4u) for details

**Comment by way0utwest** [comment]
obrigado. 

Just reg link for users to get tickets. Perhaps like this one: https://bit.ly/SQLSATSP2023TKT

**Comment by way0utwest** [comment]
If you drop me an email at admin @ sqlsaturday.com, I'll get you a list of sponsors as well.

**Comment by fabricio-powertuning** [comment]
Hi Steve,

We will have some help with external sponsors to our event? (like Microsoft or redgate)




Our event will be showed on this list?

***@***.***

Atenciosamente,


***@***.***

De: Steve Jones ***@***.***>
Enviada em: terça-feira, 22 de agosto de 2023 17:32
Para: sqlsaturday/sqlsatwebsite ***@***.***>
Cc: Fabricio Lima ***@***.***>; Author ***@***.***>
Assunto: Re: [sqlsaturday/sqlsatwebsite] SQLSaturday Vitória 2023 (Issue #233)


If you drop me an email at admin @ sqlsaturday.com, I'll get you a list of sponsors as well.

**Comment by way0utwest** [comment]
event complete - attendance added to [https://github.com/sqlsaturday/sqlsatwebsite/blob/main/assets/misc/2023/2023_Attendance.xlsx](https://github.com/sqlsaturday/sqlsatwebsite/blob/main/assets/misc/2023/2023_Attendance.xlsx)
