### ISSUE TITLE
Sao Paulo 2023

### ISSUE THREAD

**Issue by marceloadade** [sqlsaturday/sqlsatwebsite#238]
[Sao Paulo 2023 - EventChecklist.xlsx](https://github.com/sqlsaturday/sqlsatwebsite/files/12362393/Sao.Paulo.2023.-.EventChecklist.xlsx)

Hi Steve, requesting the addition of Sao Paulo's SQLSAT. Let me know if you see any issues. I am still updating the main site.
Thanks!

**Comment by way0utwest** [comment]
1067 set up. Test page up at: https://sqlsaturday.com/2023-11-25-sqlsaturday1067/

Let me know what changes you need, and when to turn this live. I can list this as soon as you approve.

**Comment by marceloadade** [comment]
Hi Steve, good morning!
I updated the sheet with the links, re-attaching it here.
Here are the details:

- Main event registration URL: https://bit.ly/SQLSATSP2023TKT
- C4P URL: https://bit.ly/sqlsatsp2023speak
- Sponsorship options URL: https://bit.ly/sqlsatsp2023sponsor

You can make the page official! 

Thank you very much!
Marcelo

[Sao Paulo 2023 - EventChecklist.xlsx](https://github.com/sqlsaturday/sqlsatwebsite/files/12408458/Sao.Paulo.2023.-.EventChecklist.xlsx)

**Comment by way0utwest** [comment]
All updated.

**Comment by way0utwest** [comment]
BTW, I think if you update the spreadsheet but don’t add to the issue, it doesn’t notify me.
