### ISSUE TITLE
SQL Saturday Atlanta 2024

### ISSUE THREAD

**Issue by robvolk-snorg** [sqlsaturday/sqlsatwebsite#263]
Hello,

Requesting new event to be set up for Atlanta 2024.  Event specifics are:

Event Title | SQL Saturday Atlanta 2024
Event Date | April 20, 2024
Event Time | 8:00 AM
Event Capacity | 700
CFP URL | https://sessionize.com/sql-saturday-atlanta-2024/
CFP End Date | February 10, 2024
Event Location | Innovation Academy, 125 Milton Ave, Alpharetta, GA 30009

Have also filled out Excel workbook and attached to this issue with additional details. Please let me know if you need this information in another format.

-Rob Volk

**Comment by way0utwest** [comment]
No XLSX attached. Test site here: https://sqlsaturday.com/2024-04-20-sqlsaturday1072/

Feel free to attach here or email admin@sqlsaturday.com

**Comment by robvolk-snorg** [comment]
Apologies, I attached it to this reply.

-Rob Volk

**Comment by robvolk-snorg** [comment]
Trying attachment one more time, will also try sending via other means.

Our Call for Speakers doesn't open until November 12, so no need to publish
before then.

Thanks.

-Rob Volk

**Comment by way0utwest** [comment]
Updated and live based on the XLS. If you need changes, please feel free to reach out. I'll post the CFS in a few places.

**Comment by way0utwest** [comment]
event complete
