### ISSUE TITLE
Update dates for Summit 2024 

### ISSUE THREAD

**Issue by TonyWSQL** [sqlsaturday/sqlsatwebsite#305]
https://github.com/sqlsaturday/sqlsatwebsite/blob/b1f09fecbafda348c4526f94dbbd8c63b357f869/_data/otherevents.yml#L68

Looks like these need updated to Nov 4-8

**Comment by way0utwest** [comment]
Thanks, good catch.

**Comment by way0utwest** [comment]
fixed
