### ISSUE TITLE
SQL Saturday Richmond 2024

### ISSUE THREAD

**Issue by jamie-wick** [sqlsaturday/sqlsatwebsite#330]
SQL Saturday RVA 2024
May 17-18 2024
Reynolds Community College - 1651 E Parham Rd, Richmond, VA 23228

SQL Saturday RVA (Richmond, Virginia) is a free one-day training event for IT professionals and students interested in the Microsoft data platform (SQL Server Databases, Business Intelligence, Data Analytics, and more).

Call For Speakers: https://sessionize.com/sql-saturday-rva-2024/
CFS End Date: March 31st
Organizers: Richmond SQL Server Users Group
Contact: sqlsatrva@richmondsql.info
Code of Conduct: same as previous event

**Comment by way0utwest** [comment]
Event complete
