### ISSUE TITLE
SQL Saturday South Florida 2024

### ISSUE THREAD

**Issue by dibetan** [sqlsaturday/sqlsatwebsite#344]
June 29th., 2024
Nova Southeastern University
[EventChecklist (1).xlsx](https://github.com/sqlsaturday/sqlsatwebsite/files/14473840/EventChecklist.1.xlsx)
![1500x500](https://github.com/sqlsaturday/sqlsatwebsite/assets/30936821/f54290e6-5a87-4588-9d5d-011dbd27c015)

**Comment by way0utwest** [comment]
Test event up at: https://sqlsaturday.com/2024-06-29-sqlsaturday1080/

**Comment by way0utwest** [comment]
Checking to see if you have a schedule here yet?

**Comment by way0utwest** [comment]
Event complete
