### ISSUE TITLE
SQLSaturday Wellington 2024

### ISSUE THREAD

**Issue by shantha05** [sqlsaturday/sqlsatwebsite#447]
I have provided the details in the attached file.
[EventChecklist.xlsx](https://github.com/sqlsaturday/sqlsatwebsite/files/15396657/EventChecklist.xlsx)
![SQLSaturday-Wellington](https://github.com/sqlsaturday/sqlsatwebsite/assets/12005609/ebfafbe9-68ea-427b-8665-3ff080686733)

**Comment by way0utwest** [comment]
Event live at https://sqlsaturday.com/2024-08-03-sqlsaturday1091/

Let me know if you need changes or feel free to submit PRs.

**Comment by shantha05** [comment]
Thanks Steve. Will do

**Comment by way0utwest** [comment]
Checking in to see how things are going and if you have a schedule ready in sessionize to post?

**Comment by shantha05** [comment]
Hi Steve

Yes, it will be published this weekend.

Anu

**Comment by way0utwest** [comment]
Excellent and thanks. I've submitted the SoW to MS, but they are moving slow. I hope to have an update next week.

When you publish, can you send the API to admin@sqlsaturday.com? It should be something like: https://sessionize.com/api/v2/1ibmnu52/view/GridSmart

**Comment by way0utwest** [comment]
I have sponsorship money. Please email admin@sqlsaturday.com to transfer this.

**Comment by way0utwest** [comment]
Event complete
