### ISSUE TITLE
SQL Saturday Syracuse 2024

### ISSUE THREAD

**Issue by Ash-a11** [sqlsaturday/sqlsatwebsite#532]
[EventChecklist - SQL Saturday Syracuse 2024 - Copy.xlsx](https://github.com/user-attachments/files/16073601/EventChecklist.-.SQL.Saturday.Syracuse.2024.-.Copy.xlsx)

**Comment by way0utwest** [comment]
Thanks for this. A couple items.

The CFS link should be a place for speakers to submit sessions. You have the same registration URL for tickets, which doesn't help speakers. Please create an event (free) on Sessionize an publish a CFS. I'd end this in early Aug so you can publish a schedule.

Test event created here: https://sqlsaturday.com/2024-09-07-sqlsaturday1095/

Check and let me know what changes. Email admin@sqlsaturday.com for a list of sponsor contacts

**Comment by Ash-a11** [comment]
So my github issue worked? Good deal! I didn't think it would.

I will go and create an event sessionize now. Also, the date on the site
page has a wrong date; the event is Sept 7th, 2024.

Many thanks,
Analyse

**Comment by Ash-a11** [comment]
When I click on the hyperlink to go to my specific event is when I see Oct
12, 2024.

**Comment by Ash-a11** [comment]
> Thanks for this. A couple items.
> 
> The CFS link should be a place for speakers to submit sessions. You have the same registration URL for tickets, which doesn't help speakers. Please create an event (free) on Sessionize an publish a CFS. I'd end this in early Aug so you can publish a schedule.
> 
> Test event created here: https://sqlsaturday.com/2024-09-07-sqlsaturday1095/
> 
> Check and let me know what changes. Email [admin@sqlsaturday.com](mailto:admin@sqlsaturday.com) for a list of sponsor contacts

The only thing I noticed was that once I click the link for the event, it shows 'Oct 12, 2024' as the date. Everything else is fine! Thank you so much for your help!

**Comment by Ash-a11** [comment]
Is it okay for me to use the SQL Saturday logo?

**Comment by way0utwest** [comment]
Yeah, saw that. Copied this from another event and forgot to change it there. It should be fixed.

I’ll also set sqlsaturday.com/Syracuse as a shortlink.

Steve Jones
Redgate Software

***@***.***<https://www.redgate.com/>

Twitter<https://twitter.com/way0utwest>    |   LinkedIn<https://www.linkedin.com/in/way0utwest>   |   YouTube<https://www.youtube.com/user/RedGateVideos>

**Comment by way0utwest** [comment]
Absolutely. Different versions here:
https://blog.sqlsaturday.com/branding/
Steve Jones
Redgate Software

***@***.***<https://www.redgate.com/>

Twitter<https://twitter.com/way0utwest>    |   LinkedIn<https://www.linkedin.com/in/way0utwest>   |   YouTube<https://www.youtube.com/user/RedGateVideos>

**Comment by Ash-a11** [comment]
my last question for now, how do I get my sessionize event out of test mode?

**Comment by way0utwest** [comment]
Hmmm, I can’t quite remember.

I think they’ve changed. This page (https://sessionize.com/playbook/getting-started#create-an-event-0), shows the need to activate. I think that you have to submit for a free event to get a license.

Steve Jones
Redgate Software

***@***.***<https://www.redgate.com/>

Twitter<https://twitter.com/way0utwest>    |   LinkedIn<https://www.linkedin.com/in/way0utwest>   |   YouTube<https://www.youtube.com/user/RedGateVideos>

**Comment by Ash-a11** [comment]
You were correct, Steve. I made an activation request this morning and now
it's working fine.

**Comment by way0utwest** [comment]
Site updated

**Comment by Ash-a11** [comment]
Awesome, thanks for the update!

**Comment by alevyinroc** [comment]
Under Sponsorship Plan, the date still shows as October 12

**Comment by Ash-a11** [comment]
Hey Steve,

I'm having an issue changing my event capacity, by any chance do you know
how to do that? I want more tickets available to sign up, especially since
the page is saying the tickets are sold out.

Thank you in advance for your help!

Best,
Analyse

**Comment by Ash-a11** [comment]
It seems there is a cap of 25 free tickets available. After that, you've
got to pay for additional tickets.

**Comment by Ash-a11** [comment]
Good deal, thank you!

**Comment by Ash-a11** [comment]
Hey Steve,

Do you have any advice? I wanted to know if you have any suggestions on how
I can get more speakers.

Best,
Analyse

**Comment by way0utwest** [comment]
You need some local and remote marketing. I’d make sure the Toronto, Albany, and other groups post about it. You can ping people in Pittsburgh, Chicago, Boston, and other relatively close places. That might help a few people be aware of the event. I’d send a few repeat messages as well.

The other thing is to limit the number of tracks. A lot of people do as many tracks as they can and end up with lots of speakers and rooms with 5 people in them. Fewer rooms and sessions always helps.

How many people have submitted?


Feel free to continue this in email (president@)

**Comment by Ash-a11** [comment]
I was considering doing 5 tracks, would that be too much? As of right now,
I have only gotten 3 people to volunteer as a speaker.

**Comment by Ash-a11** [comment]
I do anticipate the event to be on the smaller size, I set my goal for at
least 25 people to come. When next year comes around, I'll aim for a higher
amount.

**Comment by Ash-a11** [comment]
Lastly, when coming to the event program, are there any specific colors I
need to be cognizant of? I am going to create a schedule program via Canva.

**Comment by way0utwest** [comment]
OK, let's tackle these.
 With 3 speakers, you are likely doing 1 track. Maybe 2, but there should be 4-5 sessions during the day and each speaker can likely do 2. More than that is a lot. You're better off with fewer tracks. I would email out to the Albany, Pittsburgh, and other groups in the area asking for speakers.

25 people is a nice start, it's a fine goal for the first event.

For the program, I assume you mean schedule? Do the schedule in Sessionize, not anywhere else. No need to spend time there.

**Comment by Ash-a11** [comment]
Steve,

I have a positive update. In Sessionize, I noticed that 10 submissions were
made, including the 3 from the people who emailed me. I didn't receive an
email notification, so I didn't realize submission had been made until I
logged in. I'll email Pittsburgh. As for Albany, I will be attending the
event and plan to invite anyone I meet there, as well as the speakers.

And yes, I meant schedule. I'll add the schedule to Sessionize today. I
asked about that in order to provide them to attendees upon arrival, in
addition to being a way to promote the event.

**Comment by way0utwest** [comment]
Once you publish the schedule in Sessionize, create an API endpoint for embed and send me the code. If you want to print schedules, I'd print 1 large one for each room. Most people will find the schedule here, day of event: https://sqlsaturday.com/2024-09-07-sqlsaturday1095/#schedule

Glad you have a few more. I'd still set 4-5 sessions for the day (9-10, 1015-1115, etc.) and then see how many tracks you need. Less is better, getting more people into session rooms

**Comment by Ash-a11** [comment]
By any chance, do you have the logo that says SQL Saturday Syracuse?

**Comment by Ash-a11** [comment]
Also, this is the schedule.

**Comment by way0utwest** [comment]
We don't have city specific logos. We have some here you can use/modify: https://blog.sqlsaturday.com/branding/

I do not see a schedule. Please post or email the embed endpoint, which should be something like: https://sessionize.com/api/v2/6nwcjhdf/view/GridSmart

**Comment by Ash-a11** [comment]
Awesome, thank you so much!

**Comment by Ash-a11** [comment]
Good morning Steve,

I really appreciate all your help. I'm trying to find someone who can
supply me with some knick-knacks from the sponsors (like stickers, etc).
Can you help me with that?

Thank you!

-Analyse

**Comment by way0utwest** [comment]
Please email as I don't want to post contacts here.

**Comment by Ash-a11** [comment]
***@***.***?

**Comment by way0utwest** [comment]
This hides emails. president@

**Comment by way0utwest** [comment]
Event complete
