### ISSUE TITLE
Schedule is available now

### ISSUE THREAD

**Issue by shantha05** [sqlsaturday/sqlsatwebsite#546]
<script type="text/javascript" src="https://sessionize.com/api/v2/tmp3n6g1/view/GridSmart"></script>

**Comment by way0utwest** [comment]
I'm not sure you published this in sessionize as I don't see any data from this URL.

**Comment by way0utwest** [comment]
I'll try to re-edit this.

**Comment by shantha05** [comment]
Sorry, I had that as embedded HTML. Changed it to JSON output

**Comment by way0utwest** [comment]
It needs to be an embed API, not JSON

**Comment by shantha05** [comment]
Sorry, I have these options in Sessionize. 

- Embed Styled HTML, 
- Styled HTML, 
- Plain Text, 
- Embed Vanilla HTML, 
- Vanilla HTML, 
- JSON, 
- XML, 
- iCalendar 

Which one to choose?

**Comment by way0utwest** [comment]
Embed Styled HTML,

**Comment by shantha05** [comment]
Cool. Thanks Steve. Finally, it worked

**Comment by way0utwest** [comment]
Cheers. Glad it's up.
