### ISSUE TITLE
SQL Saturday Belo Horizonte 2024

### ISSUE THREAD

**Issue by maruanafif** [sqlsaturday/sqlsatwebsite#577]
[EventChecklist_SQLBH2024.xlsx](https://github.com/user-attachments/files/16355476/EventChecklist_SQLBH2024.xlsx)

**Comment by maruanafif** [comment]
@way0utwest  Hey, Could you publish our event? other information will be sent soon.

**Comment by way0utwest** [comment]
This is live

**Comment by maruanafif** [comment]
@way0utwest 
follow the registration information.

* Call for Speakers
https://sessionize.com/sql-saturday-belo-horizonte-2024/

* Listening Participants
*https://www.sympla.com.br/sql-saturday-belo-horizonte-2024-1097__2597146

**Comment by way0utwest** [comment]
The site is updated with the links.

**Comment by way0utwest** [comment]
@maruanafif Updated. Hope things go well

**Comment by maruanafif** [comment]
@way0utwest 
follow the data.
logos of sponsors and their websites.

Sponsors Website = GOLD
Otus7 = https://otus7.com/
Engenharia de dados = https://engenhariadedadosacademy.com/
Fiap = https://www.fiap.com.br/
DATAX = https://www.linkedin.com/company/eventodatax/

Sponsors Website = SILVER
Pythian = https://www.pythian.com/

Sponsors Website = free organizer
Seu Chatgpt =  https://sulamitadantas.com.br/
DGA = https://www.dgasolutions.com.br/

**Comment by maruanafif** [comment]
![DATAX](https://github.com/user-attachments/assets/2b7b63c8-4cf1-42ea-baaa-2e9336daaa07)
![engenharia-de-dados-academy-](https://github.com/user-attachments/assets/01e5406d-ed66-4a73-a537-d7a9929f45e6)
![Fiap](https://github.com/user-attachments/assets/44dcf39d-e64a-4ffe-a7c8-c249e8a756ea)
![pythian](https://github.com/user-attachments/assets/f84ca74f-ccc7-49a2-a6d0-fff626687d7b)
![seuchat](https://github.com/user-attachments/assets/548846f5-d540-4ef7-88dc-653dc4a4fea0)
![Otus7](https://github.com/user-attachments/assets/f13dd918-0d6a-4a1b-bad4-0043bd0ff3c6)
![DGA](https://github.com/user-attachments/assets/a19ae6bf-0457-4762-8c6e-93225a96562d)

**Comment by maruanafif** [comment]
@way0utwest 
see if you can download the images

**Comment by maruanafif** [comment]
@way0utwest 

Please update the website and only use this list

Follow the official list of volunteer names

Bernardo Zschaber
Fábio Sousa
Juliana Felix
Rafael Cardoso
Reinilson Júnior
Rodrigo Araújo
Tiago Morais

**Comment by way0utwest** [comment]
Please name them approapriately. It's not always clear which is which. I have a few updated with merge #740

**Comment by maruanafif** [comment]
@way0utwest 

I sent it, now with the subject SQL Saturday Belo Horizonte 2024

**Comment by way0utwest** [comment]
Should be updated, but one of the images is very light.

**Comment by maruanafif** [comment]
@way0utwest 

I have now emailed you the adjusted logo.

**Comment by way0utwest** [comment]
Can I get an update of number registered and attended? I sent an email as well

**Comment by maruanafif** [comment]
@way0utwest 

the form was answered by a Sulamita Dantas. 

please check receipt.
