### ISSUE TITLE
SQL Saturday Vitória 2024

### ISSUE THREAD

**Issue by dirceuresende** [sqlsaturday/sqlsatwebsite#657]
[EventChecklist_SQLVitoria2024.xlsx](https://github.com/user-attachments/files/17003304/EventChecklist_SQLVitoria2024.xlsx)

Call for Speakers
https://sessionize.com/sql-saturday-vitoria-2024/

@way0utwest Hey, Could you publish our event?

**Comment by way0utwest** [comment]
This is available at: https://sqlsaturday.com/vitoria

Check and let me know if you need changes . Still need a reg URL if you are tracking registrations

**Comment by dirceuresende** [comment]
Hi @way0utwest thanks for publishing the event so fast.

We are still working on the reg URL, should be ready in the next few days and I post here.

If would like to request two changes on the Organizers session:
- Talles Valiatti is duplicated
- The twitter handle @dirceuresende should be below "Dirceu Resende" name, not below "Talles Valiatti"

**Comment by way0utwest** [comment]
I have sponsorship money for you from MS. Please email admin@sqlsat

**Comment by dirceuresende** [comment]
> This is available at: https://sqlsaturday.com/vitoria
> 
> Check and let me know if you need changes . Still need a reg URL if you are tracking registrations

Hi @way0utwest, I would like to request a few changes to the page:

Reg URL: https://dataes.com.br/inscricao

Sponsorship Plans

Bronze – R$ 750,00
- Marca exposta em todos os slides das palestras com menos destaque
- Marca exposta no material de divulgacao do evento
- Distribuição de material impresso junto ao kit dos participantes
- Sua logomarca no site do evento e também no PPT do evento e palestrantes;
- Mailing List dos participantes que aceitarem receber contato de patrocinadores

Prata: R$ 1.500,00
- Todos os benefícios do Bronze
- Marca exposta com mais destaque no slide das palestras
- Possibilidade de doar brindes de sua empresa para serem sorteados ao final do evento
- Será permitido exposição de banner, distribuição de cartões de visita, flyers e brindes aos participantes

Ouro: R$ 2.200,00
- Todos os benefícios do Bronze e do Prata
- Direito a colocar uma mesa no evento para apresentação da marca/produtos
- Espaço de 5 minutos para apresentar seus produtos e serviços no início do evento
- Sua logomarca na manga da camisa dos palestrantes

Thanks!!

**Comment by way0utwest** [comment]
event complete
