### ISSUE TITLE
Denver 2022

### ISSUE THREAD

**Issue by weederbug** [sqlsaturday/sqlsatwebsite#67]
Should have Sessionize up as soon as they review for the free goodness.  Modify anything as you need to and then I'll get things updated as we progress.  Also will be sending an email your way 👯 

Event Title	Denver 2022
Event Date	September 17, 2022
Event Time	0830 MST - 0430 MST 
CFP URL	
CFP End Date	
Registration URL	
Event Location	Cherry Creek Presbyterian Church
Event Description	Making all your SQL and Azure dreams come true
Organizer Name	Denver SQL Users Group
Contact Email	board@denversql.org

**Comment by way0utwest** [comment]
event complete
