### ISSUE TITLE
SQLSaturday RVA

### ISSUE THREAD

**Issue by jamie-wick** [sqlsaturday/sqlsatwebsite#69]
Title: SQLSaturday RVA
Date: October 22, 2022
Location: ECPI University, 11104 W Broad St, Glen Allen, VA 23060
Organizers: Richmond SQL Server Users Group - Wayne Sheffield, Az Arunachalam, Jamie Wick
Contact Email: admin@richmondsql.info
Event Capacity: 250
Description: SQL Saturday RVA (Richmond, Virginia) is a free one-day training event for IT professionals and students interested in the Microsoft data platform (SQL Server Databases, Business Intelligence, Data Analytics, and more).

Additional Details: TBA

**Comment by way0utwest** [comment]
Main things needed to get live:
- cfs link (use sessionize)
- sponsorship plan (feel free to steal from other events. I'll submit an SOW to MS for you

Other items
- Registration can wait,  but EventBrite makes this easier.
- if you want each organizer listed separately, give me a contact point. (twitter, blog, email, etc.)
- precons? Might suggest you skip, or use a local person. 

email other questions or post here.

**Comment by way0utwest** [comment]
event complete
